### PR TITLE
WIP: Added xar

### PR DESCRIPTION
**Pull request by kolaente**
This will (hopefully) fix the recent build failures we have since #23

### CODE REVIEW

**Comment by kolaente** [comment]
So it looks like the issue was we built all these libraries for osx (libtapi etc), link them to the osx compiler and then move the dir without linking them again. So when running the osx compiler, it failed since it did not find the libraries.

**Comment by naiba** [comment]
Maybe you can display folder tree at last when osxcross built done.
```
apt-get install -y tree && tree /osxcross
```

**Comment by kolaente** [comment]
@naiba yes, but that does not fix the fact that the libraries are removed after they're built. I have got it working on my local machine, just trying something out here.

**Comment by naiba** [comment]
I guess you can't use drone CI to test the result.

This is base images's hash
```
+ /usr/local/bin/docker rmi d9dfdc10a3ed434b611ce120a5b838a375d0261d
--
6759 | Untagged: d9dfdc10a3ed434b611ce120a5b838a375d0261d:latest
6760 | + /usr/local/bin/docker system prune -f
6761 | Total reclaimed space: 0B
```
This is 12.06 used `base` image's hash
```
Sending build context to Docker daemon 2.048kB
--
73 | Step 1/7 : FROM techknowlogick/xgo:base
74 | base: Pulling from techknowlogick/xgo
75 | 6abc03819f3e: Pulling fs layer
76 | 05731e63f211: Pulling fs layer
.....
9dace09c92eb: Pull complete
--
173 | Digest: sha256:c55635c94639a7a7edea805dcf24bdcd6e4d47babdd5fab03e2e1762502c4b4d
174 | Status: Downloaded newer image for techknowlogick/xgo:base


```

**Comment by kolaente** [comment]
Yeah, drone does not push the image when building for a pr, so the subsequent build will always fail since it uses the base image from docker hub. I am currently building on my local machine and it looks like it works.

**Comment by kolaente** [comment]
You can try that on your machine as well, just check out my branch and run 
```
root@ubuntu:~/xgo/docker# docker build -t techknowlogick/xgo:base base/ && docker build -t techknowlogick/xgo:go-1.12.6 go-1.12.6/
```

**Comment by naiba** [comment]
Thanks, I feel that you are active all day, pay attention to your body.

**Comment by kolaente** [comment]
@naiba I'm actually learning for my exams currently, but since building the container takes ~45min I can edit something, build it and do other stuff while it's building, so it's not much of a hassle to debug this.

But sure, I'll do that :slightly_smiling_face: 
After all, this is just something we all do in our free time, and when there is none it won't be a problem.

**Comment by kolaente** [comment]
This seems to work now, I'll try to do some more optimizations.

**Comment by kolaente** [comment]
This works when building on my local machine, it does not work on drone because drone is unable to pass the images between builld stages, it will always take the base image from docker hub when building the second stage, but the fix is in the base image.
I'm going to merge this now, since it works when I build it manually.

**Pull request merged**
