### PR TITLE
Better tests

### PR DESCRIPTION
**Pull request by kolaente**
This PR adds some basic testing. It also adds running these tests in Drone.

### CODE REVIEW

**Comment by kolaente** [comment]
I'm sure we could improve the tests in `testsuite.go`, but for now, some basic tests are better than no tests.

**Comment by kolaente** [comment]
The testsuite is failing currently, we somehow have to get docker and go in one container...

**Comment by techknowlogick** [comment]
What about using something like [podman](https://podman.io/) to run xgo containers inside the image, as you don't need docker daemon access for podman.

**Comment by kolaente** [comment]
I think podman sounds like a good idea, but then we would need to make the executable path configurable first, maybe in another pr before this one.

**Comment by techknowlogick** [comment]
Closing as I'm currently working on moving CI to fully use Github Actions, and GHA allows use of raw docker commands so we can build the image in a pipeline and use it later to test

**Pull request closed without merging**
