### PR TITLE
Update go versions 1.13.4 and 1.12.13

### PR DESCRIPTION
**Pull request by kolaente**

### CODE REVIEW

**Comment by ivan-w** [comment]
Hold the horses... The CI check is missing the newly introduced architectures in bootstrap.

**Comment by ivan-w** [comment]
I also have an issue with the actual ppc64le naming. I have to figure it out. Sorry for the delay.

**Comment by kolaente** [comment]
> The CI check is missing the newly introduced architectures in bootstrap.

That's because #46 is not merged yet :)

**Comment by ivan-w** [comment]
Nope.. I have another issue - I am loading the wrong cross compiler.. there is no gcc-6 for ppc64el it's minimum gcc-8 apparently ! Lemme redo this, run the CI and I'll let you know

**Comment by kolaente** [comment]
@ivan-w The CI runs every time you push to your branch, but your PR is independent of this one. This one is just updating the go versions since the golang team released minor updates for these.

**Comment by ivan-w** [comment]
I'll let you know when I am "satisfied" with the results ;)

**Comment by ivan-w** [comment]
On LTS 18.04 there is no ppc64le gcc-6 compiler... (the libs are there; but not the compiler)

**Comment by kolaente** [comment]
> I'll let you know when I am "satisfied" with the results ;)

Sure, but can we move the conversation to #46 ?

**Pull request merged**
