### PR TITLE
toolchain library fixes

### PR DESCRIPTION
**Pull request by pat-s**
ref #256

WIP, currently testing.

Tested with 

```
TARGETOS=linux TARGETARCH_XGO=arm64 TARGETARCH_BUILDX=linux/* make release-server-xgo
```

for both the arm64 and the amd64 image. Using `aarch64-linux-gnu-gcc` instead of `arm-linux-gnueabi-gcc` fails with an error so let's stick to `arm-linux-gnueabi-gcc`.

### CODE REVIEW

**Comment by pat-s** [comment]
I think some new tests would be good which test the cross-compile for all scenarios so errors can be spotted during a PR.

**Comment by pat-s** [comment]
OK so tests 5 & 7 were already broken before #255, so discarding them from the judgement of this PR (and commenting them out for the moment). (https://github.com/techknowlogick/xgo/actions/runs/11653506586/job/32445960620?pr=258)

**Comment by pat-s** [comment]
I also tried building @kolaente project but had issues during the frontend build. Without this, the `xgo` part errors due to missing deps. Hence I can't complete verify that the changes work, but the PATH issue not finding the compiler should be fixed.

**Comment by kolaente** [comment]
I've fixed the Vikunja test and commented out the other one in https://github.com/techknowlogick/xgo/pull/259 - please rebase, then this should be good to go

**Pull request merged**
