### PR TITLE
Arm64 - take2

### PR DESCRIPTION
**Pull request by pat-s**
- Only running "build images" WF for testing purposes

### CODE REVIEW

**Comment by pat-s** [comment]
🎉 Finally got it working - this time *for real*

Here's proof: https://ci.woodpecker-ci.org/repos/3780/pipeline/8876/10

An amd64 runner using the changed arm64 gcc compiler (which is also available for Ubuntu arm) to cross-compile.

Key changes are:

- Use `gcc-arm-linux-gnueabi` and `binutils-arm-linux-gnueabi` as arm compiler instead of `aarch64-linux-gnu-gcc-9`
- Remove `gcc-9-multilib` (seems unneeded and is not avail for Ubuntu arm)

I've cleaned up the PR. While it won't succeed due to push errors to Dockerhub, it should build when merging to main.

If you're unsure if everything is good you can also build distinct images of course.
In https://hub.docker.com/repository/docker/pats22/xgo I've pushed some multiarch images for testing that were also used for the above linked WP build.

**Comment by 6543** [comment]
CI fail ?

**Comment by techknowlogick** [comment]
@6543 I'm having trouble building this locally. I'm getting "patchmake" is missing, but I see it on the Ubuntu package site. Will need to dive in a bit more.

**Comment by pat-s** [comment]
I think `patchmake` is not needed. Unclear why I added it at some point...(I could reproduce the issue).
I've removed it again and the toolchain seems to build fine now (again).

Here's are some local helper commands I used for building, maybe they are of help:

```sh
### FIRST (TOOLCHAIN)
cd docker/toolchain
docker buildx build -t pats22/xgo:toolchain -f Dockerfile --platform linux/arm64 --load .
cd ../..
# publish
cd docker/toolchain
docker buildx build -t pats22/xgo:toolchain -f Dockerfile --platform linux/amd64,linux/arm64 --push .
cd ../..


### SECOND (BASE)
# 1.21.3
# load
docker buildx build -t pats22/xgo:go-1.21.3-base -f docker/go-1.21.3/Dockerfile --platform linux/arm64 --load .
# publish
docker buildx build -t pats22/xgo:go-1.21.3-base -f docker/go-1.21.3/Dockerfile --platform linux/amd64,linux/arm64 --push .


### THIRD (COMBINED)
# load
docker buildx build --build-arg VERSION=pats22/xgo:go-1.21.3 -t pats22/xgo:go-1.21.3 -f docker/build/Dockerfile --platform linux/arm64 --load .
# publish
docker buildx build --build-arg VERSION=pats22/xgo:go-1.21.3 -t pats22/xgo:go-1.21.3 -f docker/build/Dockerfile --platform linux/amd64,linux/arm64 --push .
```

**Comment by techknowlogick** [comment]
thanks for your patience during this process @pat-s 

I built the toolchain and published a temporary tag (https://hub.docker.com/layers/techknowlogick/xgo/toolchain-arm-test/images/sha256-b25050e82fb4ea32f8da82fb51036341adf0599a189232a334bd64cc4cfdc327?context=explore). Now I now need to build the specific version image, and test building some binaries.

**Comment by techknowlogick** [comment]
Now I've built the specific tag https://hub.docker.com/layers/techknowlogick/xgo/arm-1.21.4/images/sha256-ad9f0e5133ca5338d7e9a63d5697ae321a09969f8fe2b29d073d808c6d842429?context=explore for 1.21.4
Next is to build a binary and test it.

**Comment by pat-s** [comment]
We can do the testing in WP which is using xgo to cross-compile binaries. That was the initial motivation anyhow 🙂

Spoiler: with my own images this already worked fine

**Comment by techknowlogick** [comment]
I'm also getting:
```
Enabled Go module support
Using vendored Go module dependencies
Building /source/go.mod...
Compiling for linux/amd64...
# runtime/cgo
gcc: error: unrecognized command line option '-m64'
```
when building for amd64 on arm (need to test the reverse still).

**Comment by pat-s** [comment]
I remember that during the image build there were some tests which tested the functionality across different architecturs? AFAIR they succeeded so I am wondering where this now comes from 🥴

**Comment by pat-s** [comment]
@6543 there is still an issue with the gcc arm compiler last time I tried it :( I hadn't yet time or an idea how to resolve it. No action required by tech

**Comment by 6543** [comment]
uh ok :( !

**Comment by pat-s** [comment]
OK, some good news: I did another deep dive with a lot of coffee as I can't stand not solving this puzzle 🤪️

Findings:

- a valid compiler for `amd64` for both `amd64` and `arm64` hosts is `x86_64-linux-gnu-gcc`. Unfortunately, this one doesn't come in one package for `amd64` and `arm64` on Ubuntu but is bundled in `gcc-multilib-x86-64-linux-gnu` (arm) and `
- a valid compiler for `arm64` for both  `amd64` and `arm64` hosts is `arm-linux-gnueabihf-gcc`. This one is available for both archs in `gcc-arm-linux-gnueabihf`. 
- Ubuntu arm64 doesn't have packages for `gcc-mips*`, hence cross-compiling for this arch on `arm64` likely doesn't work. I did not test it though. Maybe there is also another package with a different name providing this toolchain.

I tested the following scenarios on the example of cross-compiling `woodpecker-server`:
- Host amd64 -> compile for amd64
- Host amd64 -> compile for arm64
- Host arm64 -> compile for arm64
- Host arm64 -> compile for amd64

```sh
docker run --pull=always --rm -it pats22/xgo:go-1.21.4 bash

git clone --depth 1 https://github.com/woodpecker-ci/woodpecker.git
cd woodpecker/

curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
apt install -y nodejs
curl -fsSL https://get.pnpm.io/install.sh | bash -
source /root/.bashrc

make build-ui

TARGETOS=linux TARGETARCH_XGO=amd64 TARGETARCH_BUILDX=linux/amd64 make release-server-xgo
rm -rf /deps
TARGETOS=linux TARGETARCH_XGO=arm64 TARGETARCH_BUILDX=linux/arm64 make release-server-xgo
```

I also ran a build using the image above directly in Woodpeckers CI (using the amd64 image): https://ci.woodpecker-ci.org/repos/3780/pipeline/11320/9. In a PR this only cross-compiles amd64 -> amd64 but this one also succeeded!

Will now rebuild images for this PR and then @techknowlogick it might be worth testing again :)

**Comment by 6543** [comment]
did a test run at https://ci.woodpecker-ci.org/repos/3780/pipeline/11566/2

**Comment by pat-s** [comment]
@techknowlogick The test run (linked by 6543) went fine WRT to xgo (the one failing step is an unrelated failure). Waiting for your feedback 🙂

**Comment by pat-s** [comment]
ping @techknowlogick

**Comment by 6543** [comment]
integration test now fails ... loksl like the testdata was not pinned - unrelated?

**Comment by pat-s** [comment]
Build failures look unrelated

```
# Fetching main repository github.com/rwcarlsen/cyan/cmd/cyan...
# go: modules disabled by GO111MODULE=off; see 'go help modules'
# /build.sh: line 114: cd: /go/src/github.com/rwcarlsen/cyan/cmd/cyan: No such file or directory

[...]

# go: downloading github.com/go-playground/locales v0.14.1
# frontend/embed.go:21:12: pattern dist: no matching files found
# Cleaning up build environment...
# chown: cannot access '/build/code.vikunja.io/api*': No such file or directory
# 2024/04/10 07:54:27 Failed to cross compile package: exit status 1.
```

**Comment by pat-s** [comment]
@techknowlogick FYI the image has been in use lately in WP itself and all cross-compile steps worked: https://ci.woodpecker-ci.org/repos/3780/pipeline/15613/9

Great to see this getting merged! Let me know if any issues occur.

**Comment by 6543** [comment]
thanks for the work !!!

**Comment by techknowlogick** [comment]
@pat-s thanks for your work on this PR and for your patience too.

**Pull request merged**
