### PR TITLE
feature/mobile: re-introducing mobile support

### PR DESCRIPTION
**Pull request by lruggieri**
This PR aims to re-introduce mobile support for Android and iOS platforms.
I am not, by any stretch of the term, a cross-compilation expert and I have almost 0 experience in mobile development so any improvement and testing to this PR is more than welcome.

The company I am working for was duplicating some code from Go to C++ in order to cross-compile on Desktop and Mobile platforms. I felt it was very time-consuming and not scalable, so I decided to look for a solution for cross-compilation in Go and found this xgo project. [Karalabe branch](https://github.com/karalabe/xgo) seemed to be no more maintained and this one seemed the most updated one, so I decided to merge (and update) the mobile support of karalabe branch here.

It seems to work very fine for both Android and iOS for the project I am using it for, which is very network-oriented (several udp/tcp/websocket/grcp and such libraries used). I would be glad to have somebody else try it out with their own project and see if I missed the inclusion of some library or made other mistakes.

**_iOS simulator is not yet supported_**, but it should not take too much time to support it as well

### CODE REVIEW

**Comment by techknowlogick** [comment]
Thanks for this PR <3

I'll hopefully get to review this PR this weekend. Do you have a repo that I could test these changes with?

**Comment by lruggieri** [comment]
Nothing publicly available I'm afraid. I could make a simple client/server project with a simple Android/iOS interface. Would you be able to run it on your side (like on AndroidStudio and Xcode) if I did?

**Comment by techknowlogick** [comment]
A simple project would be suitable, I have access to xcode and a test iOS device. Thanks again :)

**Comment by lruggieri** [comment]
Sorry for taking this much time to respond.
I started a small project [here](https://github.com/lruggieri/xgo-crossmobile). It's a simple client/server application. The purpose is to click a button on Android/iOS and spawn 2 routines, a client and a server, exchanging data, printing it on screen and quitting. The mobile part is written in Dart. It works fine on Android but I had issues making it run on iOS because of some certificate signing issue. It compiles correctly but I do not know how to proceed from there. I asked some colleagues but we do not really have a mobile expert in our team, so we couldn't figure it out in a timely manner.

**Comment by techknowlogick** [comment]
@skywalker-nick hey nick, just saw your changes here. No need to create another fork, I'm happy to merge these. Not sure why you don't think this is active. It is the only xgo fork that receives golang updates within an hour of a new go release, and it is used for several top 500 github repos.

**Comment by skywalker-nick** [comment]
@techknowlogick sorry for the misunderstanding. I know it is active, however, I have several requirements based on this PR. One is the missing iOS simulator. 2nd is to centralize dependency management. 3rd is updated MacOSSDK/iOSSDK/osxcross projects which are not maintained by xgo. I didn't know how my commits came to here instead of my forked repo. I will try to remove these stuff.

**Comment by lruggieri** [comment]
I removed the commits from @skywalker-nick and force pushed but that resulted in the PR being closed. @techknowlogick could you please help re-opening it?

**Comment by zeripath** [comment]
@lruggieri I think you will need to reopen another PR.

**Pull request closed without merging**
